name: 2021-06-16-topcoffea
channels:
  - anaconda
  - conda-forge
dependencies:
  - xxhash
  - xrootd
  - matplotlib>=3
  - numba>=0.50
  - numpy>=1.16
  - scipy>=1.1
  - pickle5
  - pip:
    - coffea==0.7.3
